name: cloudflare

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/bun.lockb')) }}

      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun install

      - name: Build
        run: bun run build
        env:
          NITRO_PRESET: cloudflare_module

      - name: Install Wrangler
        run: bun add -g wrangler@3.4.0

      - name: Publish to Cloudflare
        run: bun wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
